info:
  title: API title
  version: 0.0.1
swagger: '2.0'
produces:
  - application/xml
  - application/json
  - application/octet-stream
  - text/plain
host: 'localhost:5000'
tags:
  - name: properties
    description: Operations about properties
paths:
  /v1/properties:
    post:
      summary: Create a new Property
      description: Create a new Property
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: formData
          name: x
          description: X  coordenate
          type: string
          required: true
        - in: formData
          name: 'y'
          description: Y coordenate
          type: string
          required: true
        - in: formData
          name: title
          description: Property Title
          type: string
          required: true
        - in: formData
          name: price
          description: Property price in cents
          type: string
          required: true
        - in: formData
          name: description
          description: Property description
          type: string
          required: true
        - in: formData
          name: beds
          description: Property beds quantity
          type: string
          required: true
        - in: formData
          name: baths
          description: Property baths quantity
          type: string
          required: true
        - in: formData
          name: squareMeters
          description: Property square meters
          type: string
          required: true
      responses:
        '201':
          description: Create a new Property
      tags:
        - properties
      operationId: postV1Properties
    get:
      summary: Search properties
      description: Search properties
      produces:
        - application/json
      parameters:
        - in: query
          name: ax
          description: Coordenate point A X
          type: string
          required: true
        - in: query
          name: ay
          description: Coodernate point A Y
          type: string
          required: true
        - in: query
          name: bx
          description: Coodernate pont B X
          type: string
          required: true
        - in: query
          name: by
          description: Coordenate point B Y
          type: string
          required: true
      responses:
        '200':
          description: Search properties
      tags:
        - properties
      operationId: getV1Properties
  '/v1/properties/{id}':
    get:
      summary: GET a property
      description: GET a property
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: Property id
          type: integer
          format: int32
          required: true
      responses:
        '200':
          description: GET a property
      tags:
        - properties
      operationId: getV1PropertiesId
