development:
  clients:
    default:
      database: spotippos_dev
      hosts:
        - mongo:27017
test:
  clients:
    default:
      database: spotippos_test
      hosts:
        - mongo:27017

ci:
  clients:
    default:
      database: spotippos_ci
      hosts:
        - 127.0.0.1:27017

production:
  clients:
    default:
      database: spotippos
      hosts:
        - <%= MONGODB_URI %>
